/**
 * Last updated: 2026-04-21
 * Changes: Added a maintenance header and converted robots route comments to English.
 * Purpose: Generate the robots metadata route and point crawlers to the sitemap.
 */
import type { MetadataRoute } from "next";
import { siteUrl } from "@/src/config/seo";

// Next.js turns this metadata object into the /robots.txt response.
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
    },
    // Point crawlers to the sitemap generated by app/sitemap.ts.
    sitemap: `${siteUrl}/sitemap.xml`,
    host: siteUrl,
  };
}
